// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/apps/faqly/faqs": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/categories/upload-icon": {
    params: {};
  };
  "/app/categories": {
    params: {};
  };
  "/app/categories/:id": {
    params: {
      "id": string;
    };
  };
  "/app/additional": {
    params: {};
  };
  "/app/faqs/:id": {
    params: {
      "id": string;
    };
  };
  "/app/settings": {
    params: {};
  };
  "/app/data": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/webhooks/app/scopes_update" | "/webhooks/app/uninstalled" | "/apps/faqly/faqs" | "/auth/login" | "/auth/*" | "/app" | "/app/categories/upload-icon" | "/app/categories" | "/app/categories/:id" | "/app/additional" | "/app/faqs/:id" | "/app/settings" | "/app/data";
  };
  "routes/webhooks.app.scopes_update.jsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.app.uninstalled.jsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/apps.faqly.faqs.jsx": {
    id: "routes/apps.faqly.faqs";
    page: "/apps/faqly/faqs";
  };
  "routes/auth.login/route.jsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/_index/route.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.$.jsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/app.jsx": {
    id: "routes/app";
    page: "/app" | "/app/categories/upload-icon" | "/app/categories" | "/app/categories/:id" | "/app/additional" | "/app/faqs/:id" | "/app/settings" | "/app/data";
  };
  "routes/app.categories.upload-icon.jsx": {
    id: "routes/app.categories.upload-icon";
    page: "/app/categories/upload-icon";
  };
  "routes/app.categories._index.jsx": {
    id: "routes/app.categories._index";
    page: "/app/categories";
  };
  "routes/app.categories.$id.jsx": {
    id: "routes/app.categories.$id";
    page: "/app/categories/:id";
  };
  "routes/app.additional.jsx": {
    id: "routes/app.additional";
    page: "/app/additional";
  };
  "routes/app.faqs.$id.jsx": {
    id: "routes/app.faqs.$id";
    page: "/app/faqs/:id";
  };
  "routes/app.settings.jsx": {
    id: "routes/app.settings";
    page: "/app/settings";
  };
  "routes/app._index.jsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.data.jsx": {
    id: "routes/app.data";
    page: "/app/data";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.jsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.jsx");
  "routes/apps.faqly.faqs": typeof import("./app/routes/apps.faqly.faqs.jsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.jsx");
  "routes/_index": typeof import("./app/routes/_index/route.jsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.jsx");
  "routes/app": typeof import("./app/routes/app.jsx");
  "routes/app.categories.upload-icon": typeof import("./app/routes/app.categories.upload-icon.jsx");
  "routes/app.categories._index": typeof import("./app/routes/app.categories._index.jsx");
  "routes/app.categories.$id": typeof import("./app/routes/app.categories.$id.jsx");
  "routes/app.additional": typeof import("./app/routes/app.additional.jsx");
  "routes/app.faqs.$id": typeof import("./app/routes/app.faqs.$id.jsx");
  "routes/app.settings": typeof import("./app/routes/app.settings.jsx");
  "routes/app._index": typeof import("./app/routes/app._index.jsx");
  "routes/app.data": typeof import("./app/routes/app.data.jsx");
};